### ISSUE TITLE
spelling mistake for  setActivity method in Adapter class

### ISSUE THREAD

**Issue by maheshwarLigade** [RbkGh/WSDownloader#10]
setActivity(activity)  check spelling mistake and correct this one.  Name<maheshwar.ligade@gmail.com>

**Comment by RbkGh** [comment]
@maheshwarLigade ,where exactly ?

**Comment by maheshwarLigade** [comment]
In the RecyclerViewMediaAdapter.java at line number 97 and Line no 106

**Comment by RbkGh** [comment]
I'm closing this because there is no clarity in the issue and it has no direct performance hit on the application.

**Comment by maheshwarLigade** [comment]
In the file RecyclerViewMediaAdapter.java at line number 97 and Line no 106 spelling mistake is there.
Instead of setActivity(activity) it is setActivity(activity). (i is missing in the spelling and it causing the issue)  Please let me know if you need more information.
