### ISSUE TITLE
Save Issue

### ISSUE THREAD

**Issue by heyaditya** [RbkGh/WSDownloader#6]
If i download the file and its shows saved in gallery but it will not showing on gallary. Please HELP

**Comment by RbkGh** [comment]
Hi @heyaditya, kindly check "WsDownloader" folder, that is where it is saved. You can use a file Explorer to navigate to "/storage/emulated/0/WSDownloader" folder if you still cannot find it in the gallery. I trust this should help, but if it doesn't, kindly let me know so we know what to do next. Cheers 🍻.

**Comment by heyaditya** [comment]
YEAH! But it is not shown in gallery.

**Comment by RbkGh** [comment]
Download  "Google Photos" app, you can find it there. I think your phone gallery scans only specific folders.

**Comment by heyaditya** [comment]
Ok! Thanks can you help me for making an app like, first a mainactivity is lsitview then some one click on listview,  lots of jokes appears in next activity that is second activity

**Comment by RbkGh** [comment]
Shoot me a mail and let's talk. I will love to help you.

**Comment by heyaditya** [comment]
what's your mail id?

**Comment by RbkGh** [comment]
Give me your email, I'll contact you

**Comment by heyaditya** [comment]
guptaaditya184@gmail.com

**Comment by RbkGh** [comment]
Sent, kindly check your inbox.

**Comment by heyaditya** [comment]
Hey! There?
