### ISSUE TITLE
not able to read whatsapp  status when whatsapp folder is in internal memory

### ISSUE THREAD

**Issue by darshank26** [RbkGh/WSDownloader#8]
I am able to get status when WhatsApp app is in external memory but when I switch the location of the app to internal memory it is not able to read

**Comment by RbkGh** [comment]
Can you give more details?

**Comment by RbkGh** [comment]
Is the Whatsapp folder in the external memory still present after you switched the location to internal memory?

**Comment by darshank26** [comment]
Got it solved it was actually my phone error as it was having whatapp folder on internal as well as external memory but the code is working fine 100% :+1:
